name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: DCHook
      uses: johnnyhuy/discord-webhook@main
      with:
        webhook_url: ${{ secrets.DISCORD_HOOKURL }}
